version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - redis
  redis:
    image: redis:6.0.8-alpine3.12
    ports:
      - "6379:6379"
